band_num: 30
data_file: ../input_data/sample_FR_data.txt
default_q: 4.0
eq1_file: eq_sample.txt
eq2_file: eq_sample_f.txt
high_cutoff1: 5000.0
high_cutoff2: 3000.0
k_file: ../data/ISO_226_2023_75phon.txt
low_cutoff1: 80.0
low_cutoff2: 80.0
max_q: 8.0
min_q: 1.0
model_str: R MSP3
out: sample_FR_data_f.txt
output_folder: ../output
slope: -3.3
target: -3.0
target_file: ../data/target_curve_Flat.txt
window_oct: 0.1
